export const mattressData = [
  {
    id: 1,
    name: "Premium Hybrid",
    category: "Mattress",
    popular: true,
    images: [
      "mattressimages/premium1.jpg",
      "mattressimages/premium2.jpg",
      "mattressimages/premium3.jpg",
    ],
    intro:
      "Experience the epitome of sleep excellence with our Premium Hybrid. Impeccably crafted, it combines the plush comfort of top-tier materials and innovative support systems for an indulgent and rejuvenating night.",
    description:
      "Introducing our Premium Hybrid, a masterpiece of sleep engineering that redefines luxury and support. Meticulously crafted with top-tier materials, this mattress is designed to deliver an unparalleled sleep experience. The Premium Hybrid seamlessly blends the cloud-like comfort of premium foams with the dynamic support of advanced innerspring coils. Each layer is carefully chosen to provide a perfect balance of softness, responsiveness, and support, ensuring that every night is a journey into ultimate relaxation. The mattress adapts to your body's contours, relieving pressure points and promoting proper spinal alignment. Breathable fabrics enhance airflow, contributing to a cool and comfortable sleep environment. Elevate your sleep sanctuary with the Premium Hybrid, where opulence meets innovation. Invest in the ultimate in sleep excellence and awaken each day refreshed, revitalized, and ready to embrace life's challenges. Upgrade to the extraordinary with our Premium Hybrid mattress.",
    sizes: [
      { name: "Full", width: 6.3, height: 4.5, price: 379188, unit: "ft" },
      { name: "Queen", width: 6.3, height: 5, price: 404148, unit: "ft" },
      { name: "King", width: 6.3, height: 6, price: 444708, unit: "ft" },
      { name: "Uk King", width: 6.3, height: 5.11, price: 454708, unit: "ft" },
      { name: "Cal King", width: 6.3, height: 7, price: 483448, unit: "ft" },
      {
        name: "Uk Supreme",
        width: 6.3,
        height: 6.7,
        price: 454708,
        unit: "ft",
      },
      { name: "Supreme", width: 7, height: 7, price: 526608, unit: "ft" },
    ],
  },
  {
    id: 2,
    name: "Latex Hybrid",
    category: "Mattress",
    popular: true,
    images: [
      "mattressimages/latex1.jpg",
      "mattressimages/latex2.jpg",
      "mattressimages/latex3.jpg",
      "mattressimages/latex4.jpg",
      // "mattressimages/latex5.jpg",
    ],

    intro:
      "Indulge in the ultimate sleep luxury with our Latex Hybrid. Blending natural latex and advanced support systems, it delivers unparalleled comfort, responsive support, and a rejuvenating night's sleep.",
    description:
      "Immerse yourself in the pinnacle of sleep luxury with our Latex Hybrid. This mattress seamlessly marries the exquisite comfort of natural latex with the advanced support of a hybrid design. The responsive latex layer conforms to your body, offering optimal support and pressure relief, while the hybrid construction combines the buoyancy of latex with the stability of innerspring coils. The result is a harmonious balance of comfort and support, providing a sleep experience that transcends the ordinary. The latex component ensures breathability and temperature regulation, keeping you cool and comfortable throughout the night. Our Latex Hybrid is not just a mattress; it's a commitment to an indulgent and rejuvenating sleep experience. Elevate your nights, embrace the luxury of latex, and awaken each day revitalized and ready to face the world. Transform your sleep sanctuary with our Latex Hybrid, where unparalleled comfort meets responsive support.",
    sizes: [
      { name: "Full", width: 6.3, height: 4.5, price: 389188, unit: "ft" },
      { name: "US Queen", width: 5, height: 6.6, price: 428148, unit: "ft" },
      { name: "King", width: 6.3, height: 6, price: 467708, unit: "ft" },
      { name: "Uk King", width: 6.7, height: 5.1, price: 479708, unit: "ft" },
      { name: "Us King", width: 6.6, height: 6, price: 479708, unit: "ft" },
      { name: "Cal King", width: 6.3, height: 7, price: 499448, unit: "ft" },
      { name: "UK Cal King", width: 6, height: 7, price: 499448, unit: "ft" },
      {
        name: "Uk Supreme",
        width: 6.7,
        height: 6.7,
        price: 499448,
        unit: "ft",
      },
      { name: "Supreme", width: 7, height: 7, price: 547608, unit: "ft" },
    ],
  },
  {
    id: 3,
    name: "Hybrid Orthopedics",
    category: "Mattress",
    popular: true,
    images: [
      "mattressimages/ortho1.jpg",
      "mattressimages/ortho2.jpg",
      "mattressimages/ortho3.jpg",
      "mattressimages/ortho4.jpg",
      "mattressimages/ortho5.jpg",
    ],
    intro:
      "Elevate orthopedic comfort with our Hybrid Orthopedics. Combining advanced support technology and ergonomic design, our products provide unparalleled relief, promoting a restorative sleep experience for optimal well-being.",
    description:
      "Introducing our Hybrid Orthopedics, a revolution in sleep technology tailored for superior orthopedic support. Meticulously crafted, these products seamlessly blend the benefits of advanced materials and ergonomic design to address orthopedic concerns and enhance overall well-being. The hybrid construction combines the best features of different support systems, such as memory foam and innerspring coils, to create a customized sleep solution. The result is a perfect balance of support and comfort, precisely engineered to alleviate pressure points, promote proper spinal alignment, and offer unparalleled relief for individuals with orthopedic considerations. Our Hybrid Orthopedics range from mattresses to pillow, each thoughtfully designed to cater to specific orthopedic needs. Experience the transformative synergy of cutting-edge technology and orthopedic support, and embark on a journey to restful nights and revitalized mornings. Invest in your well-being with our Hybrid Orthopedics for a sleep experience that goes beyond the ordinary.",
    sizes: [
      { name: "Twin", width: 6.3, height: 3.5, price: 275000, unit: "ft" },
      { name: "Twin Xl", width: 6.3, height: 4, price: 305160, unit: "ft" },
      { name: "Full", width: 6.3, height: 4.5, price: 331188, unit: "ft" },
      { name: "Queen", width: 6.3, height: 5, price: 356148, unit: "ft" },
      { name: "US Queen", width: 5, height: 6.6, price: 380500, unit: "ft" },
      { name: "King", width: 6.3, height: 6, price: 396708, unit: "ft" },
      { name: "Uk King", width: 6.7, height: 5.11, price: 406708, unit: "ft" },
      { name: "Cal King", width: 6.3, height: 7, price: 438448, unit: "ft" },
      { name: "US Cal King", width: 6, height: 7, price: 435448, unit: "ft" },
      {
        name: "Uk Supreme",
        width: 6.7,
        height: 6.7,
        price: 435448,
        unit: "ft",
      },
      { name: "Supreme", width: 7, height: 7, price: 478608, unit: "ft" },
    ],
  },
  {
    id: 4,
    name: "Cooling Gel",
    category: "Mattress",
    popular: false,
    images: [
      "mattressimages/cooling1.jpg",
      "mattressimages/cooling2.jpg",
      "mattressimages/cooling3.jpg",
      "mattressimages/cooling4.jpg",
      "mattressimages/cooling5.jpg",
    ],
    intro:
      "Immerse yourself in the serenity of our Cooling Gel Mattress. Engineered with cutting-edge cooling technology, it regulates temperature for a refreshing sleep experience, promoting optimal rest and rejuvenation.",
    description:
      "Discover the epitome of cool and comfort with our Cooling Gel Mattress. Designed to revolutionize your sleep, this mattress features advanced cooling gel technology that actively dissipates excess body heat, creating an optimal temperature balance for a refreshing and rejuvenating night's rest. The gel-infused memory foam contours to your body, providing personalized support while ensuring a cool and comfortable sleep surface. The breathable cover enhances airflow, contributing to a more comfortable sleep environment. Say goodbye to night sweats and embrace the tranquility of uninterrupted sleep. Whether you're seeking relief from hot nights or simply upgrading your sleep sanctuary, our Cooling Gel Mattress promises a harmonious blend of cutting-edge technology and blissful rest. Transform your nights, wake up refreshed, and experience the next level of cool, supportive sleep.",
    sizes: [
      { name: "Full", width: 6.3, height: 4.5, price: 435188, unit: "ft" },
      { name: "US Queen", width: 5, height: 6.6, price: 485148, unit: "ft" },
      { name: "King", width: 6.3, height: 6, price: 518405, unit: "ft" },
      { name: "Us King", width: 6.6, height: 6, price: 562100, unit: "ft" },
      { name: "Cal King", width: 6.3, height: 7, price: 593390, unit: "ft" },
      { name: "US Cal King", width: 6, height: 7, price: 593390, unit: "ft" },
      { name: "Supreme", width: 7, height: 7, price: 642627, unit: "ft" },
    ],
  },
  {
    id: 5,
    name: "Down Alternative Topper",
    category: "topper",
    popular: true,
    intro:
      "Upgrade your sleep oasis with our Down Alternative Topper. Enjoy the softness of premium fibers that mimic down's loft, providing plush comfort and gentle support for a dreamy night's rest.",
    description:
      "Introducing our Down Alternative Topper, a luxurious addition to your bedding ensemble. Immerse yourself in the sumptuous softness of premium fibers meticulously crafted to mimic the loft of traditional down. This topper combines the best of both worlds, offering cloud-like comfort without the allergens associated with natural feathers. Experience a lavish layer of softness that cradles your body, providing gentle support and enhancing your mattress's overall feel. The baffle-box construction ensures even distribution, preventing clumping and maintaining consistent fluffiness. Whether you're looking to revive an aging mattress or simply seeking an extra layer of opulence, our Down Alternative Topper promises a restful night's sleep. Embrace the coziness, relish in the hypoallergenic design, and create a haven of tranquility for rejuvenating sleep night after night.",
    images: [
      "displaypictures/downtopper1.jpg",
      "displaypictures/downtopper2.jpg",
      "displaypictures/downtopper3.jpg",
      "displaypictures/downtopper4.jpg",
      "displaypictures/downtopper6.jpg",
    ],
    sizes: [
      { name: "Twin", width: 75, height: 39, price: 79100, unit: "inch" },
      { name: "Full", width: 75, height: 54, price: 101700, unit: "inch" },
      { name: "Queen", width: 75, height: 60, price: 121900, unit: "inch" },
      { name: " King", width: 75, height: 72, price: 129800, unit: "inch" },
      { name: "Uk King", width: 79, height: 71, price: 135800, unit: "inch" },
      { name: "Cal King", width: 75, height: 84, price: 135500, unit: "inch" },
      {
        name: "Uk Supreme",
        width: 79,
        height: 79,
        price: 135500,
        unit: "inch",
      },
      { name: "Supreme", width: 84, height: 84, price: 141200, unit: "inch" },
    ],
  },

  {
    id: 6,
    name: "Memory Foam Topper",
    intro:
      "Enhance your sleep sanctuary with our Memory Foam Topper. Indulge in unparalleled comfort and support as the topper conforms to your body, relieving pressure points for a restorative night's sleep.",
    description:
      "Transform your sleep experience with our Memory Foam Topper. Crafted with cutting-edge technology, this topper adapts to your body's contours, offering personalized comfort and support. Say goodbye to restless nights as the memory foam relieves pressure points, promoting better spinal alignment. Whether you're looking to revitalize an aging mattress or add an extra layer of luxury to your bed, our Memory Foam Topper is the key to a rejuvenating night's sleep. Its hypoallergenic and breathable design ensures a fresh and comfortable sleep environment. Elevate your rest, embrace the soothing embrace of memory foam, and awaken each day feeling renewed and invigorated.",
    category: "topper",
    popular: true,
    images: [
      "displaypictures/mtopper1.jpg",
      "displaypictures/mtopper2.jpg",
      "displaypictures/mtopper3.jpg",
      "displaypictures/mtopper4.jpg",
      "displaypictures/mtopper5.jpg",
      "displaypictures/mtopper6.jpg",
      "displaypictures/mtopper7.jpg",
    ],
    sizes: [
      { name: "Twin", width: 75, height: 39, price: 112900, unit: "inch" },
      { name: "Full", width: 75, height: 54, price: 135500, unit: "inch" },
      { name: "Queen", width: 75, height: 60, price: 141200, unit: "inch" },
      { name: " King", width: 75, height: 72, price: 158100, unit: "inch" },
      { name: "Uk King", width: 79, height: 71, price: 164100, unit: "inch" },
      { name: "Cal King", width: 75, height: 84, price: 169400, unit: "inch" },
      {
        name: "Uk Supreme",
        width: 79,
        height: 79,
        price: 169400,
        unit: "inch",
      },
      { name: "Supreme", width: 84, height: 84, price: 175000, unit: "inch" },
    ],
  },

  // {
  //   name: "Orthopedic Support topper",
  //   category: "topper",
  //   type: "topper",
  //   size: "King",
  //   firmness: "Firm",
  //   price: 799.99,
  //   popular: true,
  //   image: "classic.png",
  // },

  // {
  //   name: "Adjustable Air topper",
  //   category: "topper",
  //   type: "topper",
  //   size: "California King",
  //   firmness: "Customizable",
  //   price: 1499.99,
  //   popular: true,
  //   image: "hybrid.png",
  // },

  // {
  //   name: "Firm Bamboo Charcoal topper",
  //   category: "topper",
  //   type: "topper",
  //   size: "King",
  //   firmness: "Extra Firm",
  //   price: 1199.99,
  //   popular: false,
  //   image: "cooling.png",
  // },

  // {
  //   name: "Natural Latex Hybrid topper",
  //   category: "topper",
  //   type: "topper",
  //   size: "Queen",
  //   firmness: "Medium-Firm",
  //   price: 1399.99,
  //   popular: true,
  //   image: "cooling.png",
  // },

  // {
  //   name: "Pocketed Coil Pillow Top topper",
  //   category: "topper",
  //   type: "topper",
  //   size: "Full",
  //   firmness: "Plush",
  //   price: 999.99,
  //   popular: false,
  //   image: "cooling.png",
  // },
  // {
  //   name: "Premium Plush pillow",
  //   category: "pillow",
  //   size: "Standard",
  //   firmness: "Soft",
  //   price: 49.99,
  //   popular: true,
  //   image: "cooling.png",
  // },
  // {
  //   name: "Adjustable Bed Base",
  //   category: "Bed Base",
  //   size: "Queen",
  //   type: "Adjustable",
  //   price: 799.99,
  //   popular: true,
  //   image: "hybrid.png",
  // },
  // {
  //   name: "Waterproof Mattress Protectors",
  //   category: "Protectors",
  //   size: "King",
  //   type: "Waterproof",
  //   price: 59.99,
  //   popular: false,
  //   image: "cooling.png",
  // },
];
